---
- name: Provision AI tools on server
  hosts: all

  tasks:
  - name: Install packages
    apt:
      pkg:
      - apache2
      - nginx

  - name: Install Ollama
    ansible.builtin.shell: curl -fsSL https://ollama.com/install.sh | sh
